# Generated by Django 2.0.1 on 2018-06-18 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dano',
            fields=[
                ('idDano', models.AutoField(primary_key=True, serialize=False)),
                ('dataDano', models.DateField()),
                ('descricao', models.TextField()),
                ('observacoes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('siape', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('nivelAcesso', models.IntegerField()),
                ('situacao', models.CharField(max_length=50)),
                ('senha', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('patrimonio', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('statusRecurso', models.CharField(max_length=45)),
                ('observacoes', models.TextField()),
                ('categoriaRecurso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recursos.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('idReserva', models.AutoField(primary_key=True, serialize=False)),
                ('statusReserva', models.CharField(max_length=45)),
                ('dataReserva', models.DateField()),
                ('horaReserva', models.TimeField()),
                ('observacoes', models.TextField()),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recursos.Pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='ReservaRecurso',
            fields=[
                ('idReservaRecurso', models.AutoField(primary_key=True, serialize=False)),
                ('dataEmprestimo', models.DateField()),
                ('horaEmprestimo', models.TimeField()),
                ('dataDevolucao', models.DateField()),
                ('horaDevolucao', models.TimeField()),
                ('dataDevolucaoEfetiva', models.DateField()),
                ('horaDevolucaoEfetiva', models.TimeField()),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recursos.Recurso')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recursos.Reserva')),
            ],
        ),
        migrations.AddField(
            model_name='dano',
            name='reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recursos.Reserva'),
        ),
    ]
