# Generated by Django 2.0.1 on 2018-06-20 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0002_auto_20180618_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='descricao',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='dano',
            name='observacoes',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='situacao',
            field=models.CharField(default='Regular', max_length=50),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='observacoes',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='statusRecurso',
            field=models.CharField(default='Disponivel', max_length=45),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='observacoes',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='statusReserva',
            field=models.CharField(default='Reservado', max_length=45),
        ),
        migrations.AlterField(
            model_name='reservarecurso',
            name='dataDevolucaoEfetiva',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='reservarecurso',
            name='horaDevolucaoEfetiva',
            field=models.TimeField(null=True),
        ),
    ]
