# Generated by Django 2.0.1 on 2018-06-20 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0005_auto_20180620_0927'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pessoa',
            new_name='Usuario',
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='pessoa',
            new_name='usuario',
        ),
    ]
