# Generated by Django 2.0.7 on 2018-07-24 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0008_usuario_ativo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='situacao',
        ),
        migrations.AddField(
            model_name='usuario',
            name='pendendias',
            field=models.IntegerField(default=0),
        ),
    ]
