# Generated by Django 2.0.7 on 2018-07-24 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0011_auto_20180724_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='nivelAcesso',
        ),
    ]
