# Generated by Django 2.0.7 on 2018-08-02 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0012_auto_20180724_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurso',
            name='nome',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
