# Generated by Django 2.0.7 on 2018-08-02 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0013_auto_20180802_0703'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservarecurso',
            old_name='recurso',
            new_name='recursos',
        ),
        migrations.RenameField(
            model_name='reservarecurso',
            old_name='reserva',
            new_name='reservas',
        ),
    ]
