# Generated by Django 2.0.1 on 2018-09-10 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0014_auto_20180802_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservarecurso',
            name='recursos',
        ),
        migrations.RemoveField(
            model_name='reservarecurso',
            name='reservas',
        ),
        migrations.AddField(
            model_name='reserva',
            name='dataDevolucao',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='dataDevolucaoEfetiva',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='dataEmprestimo',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='horaDevolucao',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='horaDevolucaoEfetiva',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='horaEmprestimo',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='recursos',
            field=models.ManyToManyField(to='recursos.Recurso'),
        ),
        migrations.DeleteModel(
            name='ReservaRecurso',
        ),
    ]
